### ISSUE TITLE
ERROR    Exception inside application: Cannot connect to host 127.0.0.1:3000 ssl:default [Connect call failed ('127.0.0.1', 3000)]

### ISSUE THREAD

**Issue by moimac** [QueraTeam/django-nextjs#36]
I'm getting this error when trying to run using docker, thanks in advance for your help.

ERROR    Exception inside application: Cannot connect to host 127.0.0.1:3000 ssl:default [Connect call failed ('127.0.0.1', 3000)]

My docker-compose.yml looks as follows:

```
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
      - frontend
    env_file:
      - dev.env
    volumes:
      - .:/app

  frontend:
    build: ./frontend_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend_app:/app
    env_file:
      - dev.env
    command: npm run dev -- -H 0.0.0.0

```

My asgi.py file includes:

```
if settings.DEBUG:
    NEXTJS_HOST = os.getenv("NEXTJS_HOST", "frontend")
    NEXTJS_PORT = os.getenv("NEXTJS_PORT", "3000")
    NEXTJS_URL = f"http://{NEXTJS_HOST}:{NEXTJS_PORT}"

    http_routes.insert(
        0,
        re_path(
            r"^(?:_next|__next|next).*",
            NextJSProxyHttpConsumer.as_asgi(target_url=NEXTJS_URL),
        ),
    )
    websocket_routers.insert(
        0,
        path(
            "_next/webpack-hmr",
            NextJSProxyWebsocketConsumer.as_asgi(target_url=NEXTJS_URL),
        ),
    )
```
